'use client';

import { useState, useTransition } from 'react';
import { Box, Button, Typography } from '@mui/material';
import { featureBulletinPost, reviewBulletinPost, verifyCreatorProfile } from '../actions/editorial';

type ReviewPost = { id: string; headline: string; dek: string; kind: string; author?: { name?: string | null; username?: string | null } | null; createdAt?: Date | null };
type CreatorRequest = { id: string; displayName: string; type: string; statement: string; user?: { name?: string | null; username?: string | null } | null; createdAt?: Date | null };

export default function EditorialDesk({ posts, creatorRequests, canPublish }: { posts: ReviewPost[]; creatorRequests: CreatorRequest[]; canPublish: boolean }) {
  const [pending, startTransition] = useTransition();
  const [message, setMessage] = useState<string>();
  const run = (work: () => Promise<unknown>, success: string) => startTransition(async () => { try { await work(); setMessage(success); window.location.reload(); } catch (error) { setMessage(error instanceof Error ? error.message : 'The editorial action could not be completed.'); } });

  return <Box id="editorial" sx={{ scrollMarginTop: 24, mb: { xs: 5, md: 7 } }}>
    <Typography variant="overline" sx={{ color: 'var(--bf-muted)' }}>EDITORIAL DESK / BULLETIN GOVERNANCE</Typography>
    <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', xl: 'minmax(0,1.2fr) minmax(320px,.8fr)' }, gap: 4, mt: 1.25 }}>
      <Box><Typography variant="h5" sx={{ fontWeight: 900, mb: 1 }}>Review queue</Typography><Box sx={{ borderTop: '2px solid var(--bf-text)', borderBottom: '1px solid var(--bf-divider)' }}>{posts.map((post) => <Box key={post.id} sx={{ p: { xs: 1.5, md: 2 }, borderBottom: '1px solid var(--bf-divider)' }}><Box sx={{ display: 'flex', justifyContent: 'space-between', gap: 1.5, alignItems: 'baseline' }}><Typography variant="overline" sx={{ color: 'var(--bf-muted)' }}>{post.kind.replace(/_/g, ' ')}</Typography><Typography variant="caption" sx={{ color: 'var(--bf-muted)' }}>BY {post.author?.name || post.author?.username || 'Creator'}</Typography></Box><Typography variant="body1" sx={{ mt: .35, fontWeight: 900 }}>{post.headline}</Typography><Typography variant="body2" sx={{ mt: .5, color: 'var(--bf-muted)' }}>{post.dek}</Typography><Box sx={{ display: 'flex', gap: 1, flexWrap: 'wrap', mt: 1.5 }}><Button size="small" variant="outlined" disabled={pending} onClick={() => run(() => reviewBulletinPost({ postId: post.id, decision: 'request_changes', reviewNote: 'Please revise and resubmit.' }), 'Revision request recorded.')}>REQUEST CHANGES</Button>{canPublish ? <><Button size="small" variant="contained" disabled={pending} onClick={() => run(() => reviewBulletinPost({ postId: post.id, decision: 'publish' }), 'Bulletin story published.')}>PUBLISH</Button><Button size="small" variant="outlined" disabled={pending} onClick={() => run(() => featureBulletinPost({ postId: post.id, selectionNote: 'Selected from the Editorial Desk.' }), 'Homepage feature updated.')}>FEATURE ON HOME</Button></> : null}</Box></Box>)}{posts.length === 0 ? <Typography variant="body2" sx={{ py: 2, color: 'var(--bf-muted)' }}>No Bulletin stories are awaiting review.</Typography> : null}</Box></Box>
      <Box><Typography variant="h5" sx={{ fontWeight: 900, mb: 1 }}>Creator verification</Typography><Box sx={{ borderTop: '2px solid var(--bf-text)', borderBottom: '1px solid var(--bf-divider)' }}>{creatorRequests.map((creator) => <Box key={creator.id} sx={{ p: { xs: 1.5, md: 2 }, borderBottom: '1px solid var(--bf-divider)' }}><Typography variant="overline" sx={{ color: 'var(--bf-muted)' }}>{creator.type.replace(/_/g, ' ')}</Typography><Typography variant="body1" sx={{ fontWeight: 900 }}>{creator.displayName}</Typography><Typography variant="caption" sx={{ display: 'block', color: 'var(--bf-muted)' }}>ACCOUNT / {creator.user?.name || creator.user?.username || 'Student'}</Typography><Typography variant="body2" sx={{ mt: 1 }}>{creator.statement}</Typography>{canPublish ? <Box sx={{ display: 'flex', gap: 1, mt: 1.5 }}><Button size="small" variant="contained" disabled={pending} onClick={() => run(() => verifyCreatorProfile({ profileId: creator.id, status: 'verified' }), 'Creator verified.')}>VERIFY</Button><Button size="small" variant="outlined" disabled={pending} onClick={() => run(() => verifyCreatorProfile({ profileId: creator.id, status: 'suspended', note: 'Verification was not approved.' }), 'Creator request closed.')}>DECLINE</Button></Box> : null}</Box>)}{creatorRequests.length === 0 ? <Typography variant="body2" sx={{ py: 2, color: 'var(--bf-muted)' }}>No creator requests are awaiting review.</Typography> : null}</Box></Box>
    </Box>
    {message ? <Typography role="status" variant="body2" sx={{ mt: 1.5, color: 'var(--bf-interactive)' }}>{message}</Typography> : null}
  </Box>;
}
