'use client';

import { useState, useTransition } from 'react';
import { Box, Button, TextField, Typography } from '@mui/material';
import { proposeKnowledgeCard } from '../actions/academic';

type KnowledgeCard = { id: string; subject: string; title: string; summary: string; content: string; publishedAt: Date | null };
const inputSx = { '& .MuiInputBase-root': { borderRadius: 0, color: 'var(--bf-text)' }, '& .MuiOutlinedInput-notchedOutline': { borderColor: 'var(--bf-divider)' }, '& .MuiInputLabel-root': { color: 'var(--bf-muted)' } };

export default function KnowledgeCenter({ cards, signedIn }: { cards: KnowledgeCard[]; signedIn: boolean }) {
  const [pending, startTransition] = useTransition();
  const [message, setMessage] = useState<string>();
  return <Box sx={{ maxWidth: 1440, mx: 'auto' }}>
    <Box component="header" sx={{ borderTop: '2px solid var(--bf-text)', borderBottom: '1px solid var(--bf-divider)', py: { xs: 1.5, md: 2.25 }, display: 'grid', gridTemplateColumns: { xs: '1fr', md: '160px minmax(0,1fr)' }, gap: 2 }}><Typography variant="overline" sx={{ color: 'var(--bf-muted)' }}>CURATED EXPLAINERS</Typography><Box><Typography component="h1" sx={{ fontWeight: 900, letterSpacing: '-.07em', fontSize: { xs: '2rem', md: '3rem' }, lineHeight: .95 }}>KNOWLEDGE BASE</Typography><Typography variant="body2" sx={{ mt: 1, color: 'var(--bf-muted)', maxWidth: 700 }}>Short, reviewed explainers distilled from high-quality forum discussions. Each guide is curated before it becomes part of the shared reference shelf.</Typography></Box></Box>
    <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', xl: 'minmax(0,1.35fr) minmax(340px,.65fr)' }, gap: { xs: 4, md: 6 }, mt: { xs: 3, md: 4 } }}>
      <Box component="section"><Typography variant="overline" sx={{ color: 'var(--bf-muted)' }}>PUBLISHED CARDS / {String(cards.length).padStart(2, '0')}</Typography><Box sx={{ mt: 1, borderTop: '2px solid var(--bf-text)', borderBottom: '1px solid var(--bf-divider)' }}>{cards.map((card) => <Box key={card.id} component="article" sx={{ p: { xs: 1.5, md: 2.25 }, borderBottom: '1px solid var(--bf-divider)' }}><Typography variant="overline" sx={{ color: 'var(--bf-muted)' }}>{card.subject}</Typography><Typography component="h2" variant="h6" sx={{ mt: .25, fontWeight: 900 }}>{card.title}</Typography><Typography variant="body2" sx={{ mt: .75, fontWeight: 700 }}>{card.summary}</Typography><Typography variant="body2" sx={{ mt: 1.25, color: 'var(--bf-muted)', whiteSpace: 'pre-wrap', lineHeight: 1.7 }}>{card.content}</Typography></Box>)}{cards.length === 0 ? <Typography variant="body2" sx={{ py: 2, color: 'var(--bf-muted)' }}>The knowledge shelf is being curated. Propose a strong explanation from a discussion to start it.</Typography> : null}</Box></Box>
      <Box component="aside"><Typography variant="overline" sx={{ color: 'var(--bf-muted)' }}>PROPOSE A CARD / REVIEW REQUIRED</Typography><Typography variant="body2" sx={{ mt: 1, color: 'var(--bf-muted)' }}>Turn a clear explanation into a concise guide. Drafts are never published automatically.</Typography>{signedIn ? <Box component="form" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); startTransition(async () => { try { await proposeKnowledgeCard({ subject: String(form.get('subject')), title: String(form.get('title')), summary: String(form.get('summary')), content: String(form.get('content')) }); setMessage('Knowledge-card proposal sent for review.'); (event.currentTarget as HTMLFormElement).reset(); } catch (error) { setMessage(error instanceof Error ? error.message : 'The proposal could not be submitted.'); } }); }} sx={{ mt: 2, display: 'grid', gap: 1.25 }}><TextField name="subject" label="Subject" required sx={inputSx} /><TextField name="title" label="Guide title" required sx={inputSx} /><TextField name="summary" label="One-sentence summary" required sx={inputSx} /><TextField name="content" label="Explanation" required multiline minRows={8} sx={inputSx} /><Button type="submit" variant="contained" disabled={pending} sx={{ justifySelf: 'start' }}>{pending ? 'SENDING…' : 'PROPOSE CARD'}</Button></Box> : <Typography variant="body2" sx={{ mt: 2, color: 'var(--bf-muted)' }}>Sign in to propose a knowledge card for editorial review.</Typography>}{message ? <Typography role="status" variant="body2" sx={{ mt: 1.5, color: 'var(--bf-interactive)' }}>{message}</Typography> : null}</Box>
    </Box>
  </Box>;
}
