'use client';

import { useState, useTransition } from 'react';
import { Box, Button, TextField, Typography } from '@mui/material';
import { createCircle, joinStudyCircle, requestMentorHelp, requestMentorVerification, submitPeerFeedback } from '../actions/academic';

type Circle = { id: string; subject: string; title: string; description: string; startsAt: Date; endsAt: Date; capacity: number; locationLabel: string | null; hostName: string; acceptedCount: number };
type Review = { id: string; threadTitle: string; threadSlug: string; rubric: unknown; requesterName: string; closesAt: Date | null };
type Mentor = { id: string; subjects: unknown; statement: string; displayName: string };
type Hub = { id: string; subject: string; title: string; description: string; startsAt: Date; endsAt: Date };

const inputSx = { '& .MuiInputBase-root': { borderRadius: 0, color: 'var(--bf-text)' }, '& .MuiOutlinedInput-notchedOutline': { borderColor: 'var(--bf-divider)' }, '& .MuiInputLabel-root': { color: 'var(--bf-muted)' } };
const when = (date: Date) => new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }).format(new Date(date));

export default function StudyCenter({ hubs, circles, reviews, mentors, signedIn }: { hubs: Hub[]; circles: Circle[]; reviews: Review[]; mentors: Mentor[]; signedIn: boolean }) {
  const [pending, startTransition] = useTransition();
  const [message, setMessage] = useState<string>();
  const run = (work: () => Promise<unknown>, success: string) => startTransition(async () => { try { await work(); setMessage(success); window.location.reload(); } catch (error) { setMessage(error instanceof Error ? error.message : 'The action could not be completed.'); } });
  const actionGuard = (work: () => Promise<unknown>, success: string) => signedIn ? run(work, success) : setMessage('Sign in to use this study feature.');

  return <Box sx={{ maxWidth: 1440, mx: 'auto' }}>
    <Box component="header" sx={{ borderTop: '2px solid var(--bf-text)', borderBottom: '1px solid var(--bf-divider)', py: { xs: 1.5, md: 2.25 }, display: 'grid', gridTemplateColumns: { xs: '1fr', md: '160px minmax(0,1fr)' }, gap: 2 }}><Typography variant="overline" sx={{ color: 'var(--bf-muted)' }}>FINITE COLLABORATION</Typography><Box><Typography component="h1" sx={{ fontWeight: 900, letterSpacing: '-.07em', fontSize: { xs: '2rem', md: '3rem' }, lineHeight: .95 }}>STUDY CENTER</Typography><Typography variant="body2" sx={{ mt: 1, color: 'var(--bf-muted)', maxWidth: 700 }}>Opt-in study circles, review exchanges, and verified mentors. No direct messages, public attendee lists, or endless group feeds.</Typography></Box></Box>
    {hubs.length ? <Box component="section" sx={{ mt: { xs: 3, md: 4 }, borderTop: '2px solid var(--bf-text)', borderBottom: '1px solid var(--bf-divider)' }}><Typography variant="overline" sx={{ display: 'block', p: 1.25, color: 'var(--bf-muted)' }}>ACTIVE STUDY HUBS / CURATED PROGRAMS</Typography>{hubs.map((hub) => <Box key={hub.id} sx={{ p: { xs: 1.5, md: 2 }, borderTop: '1px solid var(--bf-divider)', display: 'grid', gridTemplateColumns: { xs: '1fr', md: '120px minmax(0,1fr) auto' }, gap: 1.5, alignItems: 'baseline' }}><Typography variant="overline" sx={{ color: 'var(--bf-muted)' }}>{hub.subject}</Typography><Box><Typography variant="body1" sx={{ fontWeight: 900 }}>{hub.title}</Typography><Typography variant="body2" sx={{ mt: .5, color: 'var(--bf-muted)' }}>{hub.description}</Typography></Box><Typography variant="caption" sx={{ color: 'var(--bf-muted)' }}>{when(hub.startsAt)} — {when(hub.endsAt)}</Typography></Box>)}</Box> : null}
    <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', xl: 'minmax(0,1fr) minmax(0,1fr)' }, gap: { xs: 4, md: 6 }, mt: { xs: 3, md: 4 } }}>
      <Box component="section"><Typography variant="overline" sx={{ color: 'var(--bf-muted)' }}>STUDY CIRCLES / TIME-BOXED</Typography><Box sx={{ mt: 1, borderTop: '2px solid var(--bf-text)', borderBottom: '1px solid var(--bf-divider)' }}>{circles.map((circle) => <Box key={circle.id} sx={{ p: { xs: 1.5, md: 2 }, borderBottom: '1px solid var(--bf-divider)' }}><Box sx={{ display: 'flex', justifyContent: 'space-between', gap: 1 }}><Typography variant="body1" sx={{ fontWeight: 900 }}>{circle.title}</Typography><Typography variant="overline" sx={{ color: 'var(--bf-muted)' }}>{circle.subject}</Typography></Box><Typography variant="body2" sx={{ mt: .75, color: 'var(--bf-muted)' }}>{circle.description}</Typography><Typography variant="caption" sx={{ display: 'block', mt: 1 }}>HOST / {circle.hostName} · {when(circle.startsAt)} · {circle.acceptedCount + 1}/{circle.capacity} students</Typography>{circle.locationLabel ? <Typography variant="caption" sx={{ display: 'block', color: 'var(--bf-muted)' }}>LOCATION / {circle.locationLabel}</Typography> : null}<Button size="small" variant="outlined" disabled={pending} sx={{ mt: 1.25 }} onClick={() => actionGuard(() => joinStudyCircle(circle.id), 'Request sent to the study-circle host.')}>REQUEST TO JOIN</Button></Box>)}{circles.length === 0 ? <Typography variant="body2" sx={{ py: 2, color: 'var(--bf-muted)' }}>No open study circles right now.</Typography> : null}</Box>
        <Box component="form" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); actionGuard(() => createCircle({ subject: String(form.get('subject')), title: String(form.get('title')), description: String(form.get('description')), startsAt: String(form.get('startsAt')), endsAt: String(form.get('endsAt')), capacity: Number(form.get('capacity')), locationLabel: String(form.get('location') || '') }), 'Study circle opened for requests.'); }} sx={{ mt: 2, display: 'grid', gridTemplateColumns: { xs: '1fr', sm: '1fr 1fr' }, gap: 1.25 }}><Typography variant="overline" sx={{ gridColumn: '1 / -1', color: 'var(--bf-muted)' }}>OPEN A STUDY CIRCLE</Typography><TextField name="title" label="Title" required sx={{ ...inputSx, gridColumn: { xs: '1 / -1', sm: 'auto' } }} /><TextField name="subject" label="Subject" required sx={inputSx} /><TextField name="startsAt" label="Starts" type="datetime-local" required slotProps={{ inputLabel: { shrink: true } }} sx={inputSx} /><TextField name="endsAt" label="Ends" type="datetime-local" required slotProps={{ inputLabel: { shrink: true } }} sx={inputSx} /><TextField name="capacity" label="Capacity" type="number" defaultValue={4} required slotProps={{ htmlInput: { min: 2, max: 12 } }} sx={inputSx} /><TextField name="location" label="Campus-safe location label" sx={inputSx} /><TextField name="description" label="Purpose and plan" required multiline minRows={3} sx={{ ...inputSx, gridColumn: '1 / -1' }} /><Button type="submit" variant="contained" disabled={pending} sx={{ justifySelf: 'start' }}>OPEN CIRCLE</Button></Box>
      </Box>
      <Box component="section"><Typography variant="overline" sx={{ color: 'var(--bf-muted)' }}>PEER REVIEW / ACTIONABLE FEEDBACK</Typography><Box sx={{ mt: 1, borderTop: '2px solid var(--bf-text)', borderBottom: '1px solid var(--bf-divider)' }}>{reviews.map((review) => <Box key={review.id} sx={{ p: { xs: 1.5, md: 2 }, borderBottom: '1px solid var(--bf-divider)' }}><Typography variant="body1" sx={{ fontWeight: 900 }}>{review.threadTitle}</Typography><Typography variant="caption" sx={{ color: 'var(--bf-muted)' }}>REQUESTED BY {review.requesterName}</Typography><Typography variant="body2" sx={{ mt: .75 }}>RUBRIC / {Array.isArray(review.rubric) ? review.rubric.join(' · ') : 'General feedback'}</Typography><Box component="form" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); actionGuard(() => submitPeerFeedback({ reviewId: review.id, criterion: String(form.get('criterion')), feedback: String(form.get('feedback')) }), 'Feedback submitted.'); }} sx={{ display: 'grid', gap: 1, mt: 1.25 }}><TextField name="criterion" label="Criterion" required sx={inputSx} /><TextField name="feedback" label="Specific, actionable feedback" multiline minRows={3} required sx={inputSx} /><Button type="submit" variant="outlined" disabled={pending} sx={{ justifySelf: 'start' }}>SUBMIT FEEDBACK</Button></Box></Box>)}{reviews.length === 0 ? <Typography variant="body2" sx={{ py: 2, color: 'var(--bf-muted)' }}>No peer-review exchanges are open.</Typography> : null}</Box>
        <Box sx={{ mt: 3 }}><Typography variant="overline" sx={{ color: 'var(--bf-muted)' }}>VERIFIED MENTORS / OPT-IN REQUESTS</Typography><Box sx={{ mt: 1, borderTop: '2px solid var(--bf-text)', borderBottom: '1px solid var(--bf-divider)' }}>{mentors.map((mentor) => <Box key={mentor.id} sx={{ p: { xs: 1.5, md: 2 }, borderBottom: '1px solid var(--bf-divider)' }}><Typography variant="body1" sx={{ fontWeight: 900 }}>{mentor.displayName}</Typography><Typography variant="caption" sx={{ color: 'var(--bf-muted)' }}>SUBJECTS / {Array.isArray(mentor.subjects) ? mentor.subjects.join(' · ') : 'Academic support'}</Typography><Typography variant="body2" sx={{ mt: .75, color: 'var(--bf-muted)' }}>{mentor.statement}</Typography><Box component="form" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); actionGuard(() => requestMentorHelp({ mentorProfileId: mentor.id, subject: String(form.get('subject')), question: String(form.get('question')) }), 'Mentor request submitted.'); }} sx={{ display: 'grid', gap: 1, mt: 1.25 }}><TextField name="subject" label="Subject" required sx={inputSx} /><TextField name="question" label="Focused question" multiline minRows={3} required sx={inputSx} /><Button type="submit" variant="outlined" disabled={pending} sx={{ justifySelf: 'start' }}>REQUEST HELP</Button></Box></Box>)}{mentors.length === 0 ? <Typography variant="body2" sx={{ py: 2, color: 'var(--bf-muted)' }}>Verified mentors will appear after administrator review.</Typography> : null}</Box><Box component="form" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); actionGuard(() => requestMentorVerification({ subjects: String(form.get('subjects')).split(',').map((subject) => subject.trim()).filter(Boolean), statement: String(form.get('statement')) }), 'Mentor verification request submitted for administrator review.'); }} sx={{ mt: 2, display: 'grid', gap: 1.25 }}><Typography variant="overline" sx={{ color: 'var(--bf-muted)' }}>REQUEST MENTOR VERIFICATION</Typography><TextField name="subjects" label="Subjects, comma separated" required sx={inputSx} /><TextField name="statement" label="Relevant experience and mentoring approach" required multiline minRows={4} sx={inputSx} /><Button type="submit" variant="contained" disabled={pending} sx={{ justifySelf: 'start' }}>REQUEST VERIFICATION</Button></Box></Box>
    </Box>
    {message ? <Typography role="status" variant="body2" sx={{ mt: 2, color: 'var(--bf-interactive)' }}>{message}</Typography> : null}
  </Box></Box>;
}
